-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. STALLS TABLE
create table public.stalls (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null check (category in ('Food', 'Accessories')),
  base_price integer not null,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.stalls enable row level security;
create policy "Public Stalls View" on public.stalls for select using (true);

-- 2. BIDS TABLE
create table public.bids (
  id uuid default uuid_generate_v4() primary key,
  stall_id bigint references public.stalls(id) not null,
  user_id uuid references auth.users(id) not null,
  amount integer not null,
  full_name text not null,
  phone text not null,
  gitam_mail text,
  personal_mail text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.bids enable row level security;
create policy "View Own Bids" on public.bids for select using (auth.uid() = user_id);
create policy "Submit Bid" on public.bids for insert with check (auth.uid() = user_id);
-- Allow Service Role (Edge Functions) full access
create policy "Service Role Full Access" on public.bids for all using ( auth.role() = 'service_role' );

-- 3. WINNERS TABLE
create table public.winners (
  id uuid default uuid_generate_v4() primary key,
  stall_id bigint references public.stalls(id) not null,
  user_id uuid references auth.users(id) not null,
  winning_bid_id uuid references public.bids(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.winners enable row level security;
create policy "Public Winners View" on public.winners for select using (true);

-- SEED DATA
insert into public.stalls (name, category, base_price, description) values
('Stall F1', 'Food', 5000, 'Prime location near entrance.'),
('Stall F2', 'Food', 5000, 'Spacious corner stall.'),
('Stall A1', 'Accessories', 3000, 'Near stage area.');
