-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Drop existing tables to reset schema properly
DROP TABLE IF EXISTS public.winners;
DROP TABLE IF EXISTS public.bids;
DROP TABLE IF EXISTS public.stalls;

-- 1. STALLS TABLE
create table public.stalls (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null check (category in ('Category A', 'Category B', 'Category C')),
  base_price integer not null,
  reg_fee integer not null default 0,
  size text not null default '10x10',
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.stalls enable row level security;
create policy "Public Stalls View" on public.stalls for select using (true);

-- 2. BIDS TABLE
create table public.bids (
  id uuid default uuid_generate_v4() primary key,
  stall_id bigint references public.stalls(id) not null,
  user_id uuid references auth.users(id) not null,
  amount integer not null,
  full_name text not null,
  phone text not null,

  personal_mail text,
  stall_name text,
  is_winner boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.bids enable row level security;
create policy "View Own Bids" on public.bids for select using (auth.uid() = user_id);
create policy "Submit Bid" on public.bids for insert with check (auth.uid() = user_id);
-- Admin Policies
-- Admin Policies
drop policy if exists "Admin View All" on public.bids;
create policy "Admin View All" on public.bids for select using (
  (auth.jwt() ->> 'email') in ('tejachennuru05@gmail.com', 'skmotaparthi@gmail.com', 'rkotha2@gitam.in', 'rkagula@gitam.in', 'rpininti@gitam.in')
);
drop policy if exists "Admin Update" on public.bids;
create policy "Admin Update" on public.bids for update using (
  (auth.jwt() ->> 'email') in ('tejachennuru05@gmail.com', 'skmotaparthi@gmail.com', 'rkotha2@gitam.in', 'rkagula@gitam.in', 'rpininti@gitam.in')
);

-- Service Role
create policy "Service Role Full Access" on public.bids for all using ( auth.role() = 'service_role' );

-- MIGRATION: 1. Add stall_name, 2. Backfill, 3. Drop gitam_mail (manual run required for existing DBs if not re-running schema)
-- DO THIS IF RUNNING ON EXISTING DB:
-- alter table public.bids add column if not exists stall_name text;
-- update public.bids b set stall_name = s.name from public.stalls s where b.stall_id = s.id;
-- alter table public.bids drop column if exists gitam_mail;


-- SEED DATA
insert into public.stalls (name, category, base_price, reg_fee, size, description) values
-- Category A: Base 60000, Reg 3000, Size 20x20
('Water bottles', 'Category A', 60000, 3000, '20x20', 'Premium hydration stall.'),
('Biryani', 'Category A', 60000, 3000, '20x20', 'Authentic flavor rich biryani.'),
('Ice cream', 'Category A', 60000, 3000, '20x20', 'Cool treats for everyone.'),
('Shawarma', 'Category A', 60000, 3000, '20x20', 'Hot and spicy shawarma rolls.'),

-- Category B: Base 30000, Reg 1000, Size 10x10
('Cool drinks', 'Category B', 30000, 1000, '10x10', 'Refreshing beverages.'),
('Frankie', 'Category B', 30000, 1000, '10x10', 'Delicious rolls.'),
('Waffles', 'Category B', 30000, 1000, '10x10', 'Sweet and crispy waffles.'),
('French fries and spring potatoes', 'Category B', 30000, 1000, '10x10', 'Crispy potato snacks.'),
('Tiffins', 'Category B', 30000, 1000, '10x10', 'Traditional tiffins.'),
('Goli soda', 'Category B', 30000, 1000, '10x10', 'Classic fizzy drink.'),
('Milkshakes', 'Category B', 30000, 1000, '10x10', 'Creamy milkshakes.'),
('Kebabs', 'Category B', 30000, 1000, '10x10', 'Grilled delicacies.'),
('Chaat and pani puri', 'Category B', 30000, 1000, '10x10', 'Spicy street food.'),
('Maggi', 'Category B', 30000, 1000, '10x10', 'All time favorite noodles.'),
('Fast food', 'Category B', 30000, 1000, '10x10', 'Pizza, Burgers etc.'),
('Juices', 'Category B', 30000, 1000, '10x10', 'Fresh fruit juices.'),
('Chocolate fountain', 'Category B', 30000, 1000, '10x10', 'Chocolatey delight.'),
('Tacos', 'Category B', 30000, 1000, '10x10', 'Mexican style tacos.'),
('Burgers and pizzas', 'Category B', 30000, 1000, '10x10', 'Cheesy delights.'),
('Falooda', 'Category B', 30000, 1000, '10x10', 'Rich dessert drink.'),
('Mojitos', 'Category B', 30000, 1000, '10x10', 'Non-alcoholic refreshing mix.'),

-- Category C: Base 16000, Reg 1000, Size 10x10
('Accessories', 'Category C', 16000, 1000, '10x10', 'Trendy accessories.'),
('Jewellery', 'Category C', 16000, 1000, '10x10', 'Handmade and fashion jewellery.'),
('Keychains', 'Category C', 16000, 1000, '10x10', 'Custom and fun keychains.'),
('Posters & Stickers', 'Category C', 16000, 1000, '10x10', 'Artistic prints and stickers.'),
('Bakery items', 'Category C', 16000, 1000, '10x10', 'Cakes and pastries.'),
('Flower stall', 'Category C', 16000, 1000, '10x10', 'Fresh flowers and bouquets.'),
('Photobooth', 'Category C', 16000, 1000, '10x10', 'Capture memories.'),
('Handicrafts(DIY)', 'Category C', 16000, 1000, '10x10', 'Creative DIY crafts.');
